# Generated by Django 2.0.3 on 2019-12-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15)),
                ('money', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15)),
                ('kind', models.CharField(max_length=15)),
                ('save', models.PositiveIntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Spends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15)),
                ('kind', models.CharField(max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15)),
                ('money', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
